# .github/workflows/expo-build.yml
name: Expo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Android
        run: |
          npm install -g eas-cli
          eas build --platform android --profile preview
          
      - name: Build iOS
        run: |
          eas build --platform ios --profile preview
